refactor: updating with suggestions

diff --git a/multi-container/hello-nginx-sample/tests.cloudbuild.yaml b/multi-container/hello-nginx-sample/tests.cloudbuild.yaml
--- a/multi-container/hello-nginx-sample/tests.cloudbuild.yaml
+++ b/multi-container/hello-nginx-sample/tests.cloudbuild.yaml
@@ -1,34 +1,41 @@
 steps:
-- id: 'e2e-test'
-  waitFor: ['-']
-  name: "gcr.io/cloud-builders/gcloud"
-  dir: '${_SAMPLE_DIR}'
-  script: |
-    #!/bin/bash
-    ./tests/e2e-test.sh || touch /workspace/e2e-failed
-  env:
-    - '_REGION=$_REGION'    
-    - '_SERVICE_NAME=$_SERVICE_NAME'
-- id: 'e2e-cleanup'
-  waitFor: ['e2e-test']
-  name: "gcr.io/cloud-builders/gcloud"
-  dir: '${_SAMPLE_DIR}'
-  entrypoint: './tests/e2e-cleanup.sh'
-  env:
-    - '_REGION=$_REGION'    
-    - '_SERVICE_NAME=$_SERVICE_NAME'
-- id: 'report-status'
-  waitFor: ['e2e-cleanup']
-  name: "gcr.io/cloud-builders/gcloud"
-  dir: '${_SAMPLE_DIR}'
-  script: |
-    #!/bin/bash
-    if [[ -f /workspace/e2e-failed   ]]
-    then
-      echo "Step e2e-test failed"
-      exit 1
-    fi 
-substitutions:  
-  _SERVICE_NAME: 'nginx-example'
-  _REGION: 'us-central1'
-  _SAMPLE_DIR: 'multi-container/hello-nginx-sample'
+  - id: "e2e-test"
+    waitFor: ["-"]
+    name: "gcr.io/cloud-builders/gcloud"
+    dir: "${_SAMPLE_DIR}"
+    script: |
+      #!/bin/bash
+      echo "Installing gettext-base for envsubst ..."
+      apt-get update && apt-get install gettext-base
+      echo "Run e2e-test ..."
+      ./tests/e2e-test.sh || touch /workspace/e2e-failed
+    env:
+      - "BUILD_ID=$BUILD_ID"
+      - "_REGION=$_REGION"
+      - "_SERVICE_NAME=$_SERVICE_NAME"
+  - id: "e2e-cleanup"
+    waitFor: ["e2e-test"]
+    name: "gcr.io/cloud-builders/gcloud"
+    dir: "${_SAMPLE_DIR}"
+    script: |
+      #!/bin/bash
+      export UNIQ_SERVICE_NAME="${_SERVICE_NAME}-$BUILD_ID"
+      gcloud run services delete "${UNIQ_SERVICE_NAME}" --quiet --region "${_REGION}"
+    env:
+      - "BUILD_ID=$BUILD_ID"
+      - "_REGION=$_REGION"
+      - "_SERVICE_NAME=$_SERVICE_NAME"
+  - id: "report-status"
+    waitFor: ["e2e-cleanup"]
+    name: "gcr.io/cloud-builders/gcloud"
+    script: |
+      #!/bin/bash
+      if [[ -f /workspace/e2e-failed   ]]
+      then
+        echo "Step e2e-test failed"
+        exit 1
+      fi
+substitutions:
+  _SERVICE_NAME: "nginx-mc-example-testing"
+  _REGION: "us-central1"
+  _SAMPLE_DIR: "multi-container/hello-nginx-sample"
