fix: reduce flakiness of vpc sample

diff --git a/vpc-sample/tests.cloudbuild.yaml b/vpc-sample/tests.cloudbuild.yaml
--- a/vpc-sample/tests.cloudbuild.yaml
+++ b/vpc-sample/tests.cloudbuild.yaml
@@ -71,15 +71,22 @@ steps:
 
         if grep -q "404" <<< "$msg"; then
           echo "Restricted Function Test: PASSED"
-          else echo $msg && exit 1
+        else
+          echo "Restricted Function Test: FAILED"
+          echo $msg && exit 1
         fi
+
+        # Attempt to reduce flakiness
+        sleep 10
 
         # Cloud Run service should return "Hello World" from the ingress-restricted Cloud Function via the VPC Connector.
         msg=$(curl -si --fail --show-error -H "Authorization: Bearer $(cat _id_token)" $(cat _service_url))
 
         if grep -q "Hello World" <<< "$msg"; then
           echo "VPC Function Test: PASSED"
-          else echo $msg && exit 1
+        else
+          echo "VPC Function Test: FAILED"
+          echo $msg && exit 1
         fi
     waitFor: ["Deploy to Cloud Run", "Deploy Restricted Function"]
 
